config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/about', to: 'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def show; end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = 'Article was created successfully.'
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article was updated successfully.'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_error.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
  <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg%></li>
  <% end %>
  </ul>
<% end %>

app/views/articles/_form.html.erb
<%= render 'error'%>

<%= form_with(model: @article, local: true)  do |f| %>

<p>
 <%= f.label :title %><br/>
 <%= f.text_field :title%>
</p>

<p>
  <%= f.label :description%><br/>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form'%>

<p>
<%= link_to 'Cancel and return to articles listing', articles_path %>
</p>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<p>
<%= button_to 'Create new Article', new_article_path, method: :get %>
</p>

<table>
  <thead>
    <tr>
    <th>Title</th>
    <th>Description</th>
    <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form'%>

<p>
<%= link_to 'Return to articles listing', articles_path %>
</p>

app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Title: </strong> <%= @article.title %> </p>
<p><strong>Description: </strong> <%= @article.description %> </p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %> |
<%= link_to 'Return to articles listing', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
    <%= render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

<p>
<%= link_to 'Articles listing', articles_path %> | 
<%= link_to 'Home page', root_path %>
</p>

app/views/pages/home.html.erb
<h1>Home Page</h1>

<p>
<%= link_to 'Articles listing', articles_path %> | 
<%= link_to 'About page', about_path %>
</p>